monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: [ "!event" ]
            handler: grouped
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        grouped:
            type: group
            members: [ nested, deduplicated ]
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: [ "!event", "!doctrine", "!console" ]
        deduplicated:
            type: deduplication
            handler: swift
        swift:
            type: swift_mailer
            from_email: 'pawel.liwocha@gmail.com'
            to_email: 'pawel.liwocha@gmail.com'
            subject: 'RedSky - Shorte APP - PROD - An Error Occurred!'
            level: error
            formatter: monolog.formatter.html
            content_type: text/html
